---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[graphicsmagick::depackage]
      - recipe[graphicsmagick::source]
    attributes:
  - name: package
    run_list: 
      - recipe[graphicsmagick::package]
    attributes:
  - name: depackage
    run_list:
      - recipe[graphicsmagick::depackage]
    attributes:
  - name: source
    run_list:
      - recipe[graphicsmagick::source]
    attributes:
